"""Bundled seed data for offline and fallback demonstrations."""

from __future__ import annotations

from copy import deepcopy

SOURCE_REGISTRY = {
    "compute-frontier": {"source": "Compute Frontier", "source_zh": "算力前沿网"},
    "ai-systems-weekly": {"source": "AI Systems Weekly", "source_zh": "智算周报"},
    "silicon-dispatch": {"source": "Silicon Dispatch", "source_zh": "芯片产业快讯"},
    "ev-insight": {"source": "EV Insight", "source_zh": "电驱观察"},
    "charge-network": {"source": "Charge Network Daily", "source_zh": "充电产业网"},
    "mobility-journal": {"source": "Mobility Journal", "source_zh": "智能出行观察"},
    "pitch-report": {"source": "Pitch Report", "source_zh": "球场观察"},
    "stadium-wire": {"source": "Stadium Wire", "source_zh": "场馆脉冲"},
    "fan-route": {"source": "Fan Route Review", "source_zh": "赛事商业内参"},
    "climate-desk": {"source": "Climate Desk", "source_zh": "气候瞭望"},
    "grid-watch": {"source": "Grid Watch", "source_zh": "电网观察"},
    "power-market": {"source": "Power Market Brief", "source_zh": "电力市场通"},
    "cyber-brief": {"source": "Cyber Brief", "source_zh": "安全内参"},
    "security-post": {"source": "Security Post", "source_zh": "网安邮报"},
    "threat-monitor": {"source": "Threat Monitor", "source_zh": "威胁监测站"},
    "health-next": {"source": "Health Next", "source_zh": "健康科技参考"},
    "bio-innovation": {"source": "Bio Innovation Daily", "source_zh": "生物创新日报"},
    "med-device": {"source": "Med Device Review", "source_zh": "医疗器械观察"},
    "capital-pulse": {"source": "Capital Pulse", "source_zh": "资本脉冲"},
    "fintech-scope": {"source": "Fintech Scope", "source_zh": "金融科技视野"},
    "payments-wire": {"source": "Payments Wire", "source_zh": "支付产业线"},
    "travel-loop": {"source": "Travel Loop", "source_zh": "文旅环线"},
    "culture-grid": {"source": "Culture Grid", "source_zh": "城市文化网"},
    "exhibit-lab": {"source": "Exhibit Lab", "source_zh": "展陈体验实验室"},
}


SOURCE_REGISTRY.update(
    {
        "compute-frontier": {**SOURCE_REGISTRY["compute-frontier"], "site_url": "https://www.tomshardware.com/"},
        "ai-systems-weekly": {**SOURCE_REGISTRY["ai-systems-weekly"], "site_url": "https://www.datacenterdynamics.com/en/"},
        "silicon-dispatch": {**SOURCE_REGISTRY["silicon-dispatch"], "site_url": "https://www.semiconductor-digest.com/"},
        "ev-insight": {**SOURCE_REGISTRY["ev-insight"], "site_url": "https://electrek.co/"},
        "charge-network": {**SOURCE_REGISTRY["charge-network"], "site_url": "https://insideevs.com/"},
        "mobility-journal": {**SOURCE_REGISTRY["mobility-journal"], "site_url": "https://www.smartcitiesdive.com/"},
        "pitch-report": {**SOURCE_REGISTRY["pitch-report"], "site_url": "https://www.goal.com/"},
        "stadium-wire": {**SOURCE_REGISTRY["stadium-wire"], "site_url": "https://www.stadiumdb.com/"},
        "fan-route": {**SOURCE_REGISTRY["fan-route"], "site_url": "https://www.sportbusiness.com/"},
        "climate-desk": {**SOURCE_REGISTRY["climate-desk"], "site_url": "https://www.canarymedia.com/"},
        "grid-watch": {**SOURCE_REGISTRY["grid-watch"], "site_url": "https://www.utilitydive.com/"},
        "power-market": {**SOURCE_REGISTRY["power-market"], "site_url": "https://www.powermag.com/"},
        "cyber-brief": {**SOURCE_REGISTRY["cyber-brief"], "site_url": "https://www.darkreading.com/"},
        "security-post": {**SOURCE_REGISTRY["security-post"], "site_url": "https://www.bleepingcomputer.com/"},
        "threat-monitor": {**SOURCE_REGISTRY["threat-monitor"], "site_url": "https://www.securityweek.com/"},
        "health-next": {**SOURCE_REGISTRY["health-next"], "site_url": "https://www.mobihealthnews.com/"},
        "bio-innovation": {**SOURCE_REGISTRY["bio-innovation"], "site_url": "https://www.biospace.com/"},
        "med-device": {**SOURCE_REGISTRY["med-device"], "site_url": "https://www.medtechdive.com/"},
        "capital-pulse": {**SOURCE_REGISTRY["capital-pulse"], "site_url": "https://www.bloomberg.com/markets"},
        "fintech-scope": {**SOURCE_REGISTRY["fintech-scope"], "site_url": "https://www.finextra.com/"},
        "payments-wire": {**SOURCE_REGISTRY["payments-wire"], "site_url": "https://thepaypers.com/"},
        "travel-loop": {**SOURCE_REGISTRY["travel-loop"], "site_url": "https://www.travelweekly.com/"},
        "culture-grid": {**SOURCE_REGISTRY["culture-grid"], "site_url": "https://www.theartnewspaper.com/"},
        "exhibit-lab": {**SOURCE_REGISTRY["exhibit-lab"], "site_url": "https://blooloop.com/"},
    }
)

SOURCE_REGISTRY.update(
    {
        "hupu-nba": {
            "source": "Hupu NBA",
            "source_zh": "虎扑篮球",
            "site_url": "https://nba.hupu.com/",
        },
        "nba-official": {
            "source": "NBA Official",
            "source_zh": "NBA官网",
            "site_url": "https://www.nba.com/news",
        },
        "openai-watch": {
            "source": "OpenAI Watch",
            "source_zh": "AI技术前线",
            "site_url": "https://openai.com/news/",
        },
        "model-wire": {
            "source": "Model Wire",
            "source_zh": "模型情报站",
            "site_url": "https://huggingface.co/blog",
        },
        "infra-radar": {
            "source": "Infra Radar",
            "source_zh": "算力基础设施雷达",
            "site_url": "https://www.datacenterdynamics.com/en/",
        },
        "market-expectations": {
            "source": "Market Expectations",
            "source_zh": "市场预期观察",
            "site_url": "https://www.reuters.com/markets/",
        },
        "forex-flash": {
            "source": "Forex Flash",
            "source_zh": "汇率快报",
            "site_url": "https://www.investing.com/currencies/",
        },
        "equity-sentiment": {
            "source": "Equity Sentiment",
            "source_zh": "股票情绪追踪",
            "site_url": "https://www.marketwatch.com/investing",
        },
    }
)

SOURCE_REGISTRY.update(
    {
        "macro-watch": {
            "source": "Macro Watch",
            "source_zh": "宏观利率观察",
            "site_url": "https://www.reuters.com/markets/",
        },
        "gold-watch": {
            "source": "Gold Watch",
            "source_zh": "贵金属观察",
            "site_url": "https://www.investing.com/commodities/gold",
        },
        "bond-desk": {
            "source": "Bond Desk",
            "source_zh": "债券市场台",
            "site_url": "https://www.bloomberg.com/markets/rates-bonds",
        },
    }
)


def _build_article(
    article_id: str,
    source_key: str,
    title: str,
    title_zh: str,
    summary: str,
    summary_zh: str,
    published_at: str,
) -> dict:
    source_meta = SOURCE_REGISTRY[source_key]
    return {
        "id": article_id,
        "source_id": source_key,
        "title": title,
        "title_zh": title_zh,
        "summary": summary,
        "summary_zh": summary_zh,
        "source": source_meta["source"],
        "source_zh": source_meta["source_zh"],
        "url": "",
        "source_url": source_meta.get("site_url", ""),
        "published_at": published_at,
    }


SEED_ARTICLES = [
    _build_article(
        "seed-ai-001",
        "compute-frontier",
        "AI chipmakers expand inference clusters for enterprise buyers",
        "AI 芯片厂商面向企业客户扩建推理集群",
        "Suppliers said new accelerators and efficient rack design are lifting demand for enterprise inference capacity.",
        "供应商表示，新一代加速卡和更高效的机架设计，正在带动企业级推理算力需求上升。",
        "2026-04-08",
    ),
    _build_article(
        "seed-ai-002",
        "ai-systems-weekly",
        "Liquid cooling retrofits accelerate at regional data centers",
        "区域数据中心加速推进液冷改造",
        "Operators reported faster retrofit cycles and stronger rack density for large-scale model training halls.",
        "运营方称，大模型训练机房的液冷改造周期更短、机柜密度也更高。",
        "2026-04-09",
    ),
    _build_article(
        "seed-ai-003",
        "compute-frontier",
        "Sovereign compute funds back domestic packaging and optical links",
        "主权算力基金加码先进封装与光互连",
        "Public capital is targeting packaging, photonics, and resilient domestic supply for AI infrastructure.",
        "公共资本正集中投向先进封装、光子互连与本土 AI 基础设施供应链。",
        "2026-04-10",
    ),
    _build_article(
        "seed-ai-004",
        "ai-systems-weekly",
        "Cloud operators sign long-term networking deals for multimodal workloads",
        "云服务商为多模态负载签下长期高速网络合同",
        "Stronger traffic forecasts are pushing demand for low-latency switching and memory bandwidth upgrades.",
        "由于多模态业务流量预期提升，低时延交换与高带宽内存升级需求同步增长。",
        "2026-04-11",
    ),
    _build_article(
        "seed-ev-001",
        "ev-insight",
        "Battery swapping depots gain traction among urban delivery fleets",
        "换电站模式在城市配送车队中走热",
        "Fleet operators said swapping reduces downtime and improves utilization for high-frequency delivery routes.",
        "车队运营方表示，换电可缩短停运时间，并提升高频配送线路的车辆利用率。",
        "2026-04-08",
    ),
    _build_article(
        "seed-ev-002",
        "charge-network",
        "LFP pack prices ease as recyclers scale recovery capacity",
        "随着回收能力提升，磷酸铁锂电池包价格回落",
        "Recovered lithium and better yield rates are supporting more stable battery pricing for mainstream EV models.",
        "锂回收效率提升与良率改善，正在帮助主流电动车型获得更稳定的电池成本。",
        "2026-04-09",
    ),
    _build_article(
        "seed-ev-003",
        "ev-insight",
        "Highway charging corridors add truck-friendly megawatt stations",
        "高速充电走廊新增面向电卡的兆瓦级站点",
        "Developers said truck-ready stations should ease long-haul electrification and reduce route anxiety.",
        "开发方认为，面向电动卡车的兆瓦级站点将缓解长途电动化过程中的续航焦虑。",
        "2026-04-10",
    ),
    _build_article(
        "seed-ev-004",
        "charge-network",
        "Dealers trim EV inventory after a slower discount-heavy quarter",
        "经销商在促销压力下收缩电动车库存",
        "Retailers warned that soft showroom traffic and discount pressure could delay some launch schedules.",
        "零售端警告称，客流偏弱与促销压力可能推迟部分车型的上市节奏。",
        "2026-04-11",
    ),
    _build_article(
        "seed-sport-001",
        "pitch-report",
        "Late winner keeps the title race alive in a packed weekend fixture",
        "补时绝杀让联赛争冠悬念继续延续",
        "Fans celebrated a dramatic comeback as the hosts protected momentum in the title battle.",
        "主队上演逆转后，争冠走势再度拉满，球迷情绪明显升温。",
        "2026-04-08",
    ),
    _build_article(
        "seed-sport-002",
        "stadium-wire",
        "Stadium rail upgrades move ahead before the summer tournament window",
        "夏季赛事前，场馆轨道接驳升级提速",
        "City planners said smoother fan transport should improve crowd flow and reduce entry congestion.",
        "城市规划部门表示，更顺畅的接驳系统将改善球迷集散效率并降低入场拥堵。",
        "2026-04-09",
    ),
    _build_article(
        "seed-sport-003",
        "pitch-report",
        "Youth striker earns a call-up after a two-goal breakthrough",
        "青年前锋梅开二度后获得一线队征召",
        "Academy coaches described the player as confident and decisive after a standout attacking display.",
        "青训教练评价这名球员在关键比赛中更加自信，终结效率也明显提升。",
        "2026-04-10",
    ),
    _build_article(
        "seed-sport-004",
        "stadium-wire",
        "Cup semifinal rotation plan tests squad depth and recovery rhythm",
        "杯赛半决赛轮换计划考验阵容厚度与恢复节奏",
        "Coaches said careful rotation should protect key players while keeping the team sharp.",
        "教练组认为，合理轮换能在保护核心球员的同时维持全队比赛状态。",
        "2026-04-11",
    ),
    _build_article(
        "seed-energy-001",
        "climate-desk",
        "Solar-plus-storage microgrids expand in heat-stressed districts",
        "高温高压地区加快部署光储微电网",
        "Local projects are pairing rooftop solar and batteries to improve cooling resilience during heat waves.",
        "多个社区项目通过屋顶光伏与储能结合，提高极端高温期间的供电韧性。",
        "2026-04-08",
    ),
    _build_article(
        "seed-energy-002",
        "grid-watch",
        "Offshore wind developers seek contract relief after cost surges",
        "海上风电开发商因成本上涨寻求合同缓冲",
        "Developers warned that inflation and supplier delays are adding strain to new offshore projects.",
        "开发商表示，通胀与供应延迟正在给新海上风电项目带来更大压力。",
        "2026-04-09",
    ),
    _build_article(
        "seed-energy-003",
        "climate-desk",
        "Drought and heat strain hydro output across regional grids",
        "干旱与热浪让多地水电出力承压",
        "Lower reservoir levels are raising power market risk ahead of the summer demand peak.",
        "库容下降正在推高夏季用电高峰来临前的电力市场风险。",
        "2026-04-10",
    ),
    _build_article(
        "seed-energy-004",
        "grid-watch",
        "Grid batteries smooth evening peaks for large wind corridors",
        "电网侧储能为大规模风电走廊削峰填谷",
        "Utilities said storage systems are helping reduce curtailment and stabilize evening supply.",
        "公用事业方表示，储能系统正在帮助降低弃风率并稳定晚高峰供电。",
        "2026-04-11",
    ),
    _build_article(
        "seed-security-001",
        "cyber-brief",
        "Zero-trust identity projects rise across finance and telecom groups",
        "零信任身份治理在金融与通信行业加速落地",
        "Security teams said centralized identity verification is reducing lateral movement risk in large enterprises.",
        "安全团队表示，统一身份治理正在降低大型企业中的横向移动风险。",
        "2026-04-08",
    ),
    _build_article(
        "seed-security-002",
        "security-post",
        "Ransomware gangs target outsourced hospital software vendors",
        "勒索团伙开始集中攻击医院外包软件供应商",
        "Researchers warned that healthcare vendors with weak segmentation remain attractive attack paths.",
        "研究人员警告称，分区隔离不足的医疗软件供应商仍是高风险攻击入口。",
        "2026-04-09",
    ),
    _build_article(
        "seed-security-003",
        "cyber-brief",
        "Browser isolation pilots help reduce phishing exposure in hybrid offices",
        "浏览器隔离试点帮助混合办公场景降低钓鱼风险",
        "Companies reported fewer credential theft incidents after moving risky browsing into remote sessions.",
        "多家公司表示，将高风险访问迁入远程隔离环境后，凭证被盗事件明显减少。",
        "2026-04-10",
    ),
    _build_article(
        "seed-security-004",
        "security-post",
        "Regulators tighten breach disclosure timelines for cloud contractors",
        "监管机构收紧云服务承包商的数据泄露披露时限",
        "Compliance teams said shorter disclosure windows are forcing faster incident triage and reporting workflows.",
        "合规团队指出，更短的披露窗口正在倒逼企业升级事件分级与上报流程。",
        "2026-04-11",
    ),
    _build_article(
        "seed-health-001",
        "health-next",
        "AI imaging assistants shorten review time in public hospitals",
        "AI 影像辅助系统缩短公立医院阅片时间",
        "Radiology departments said triage tools are helping prioritize urgent scans and improve throughput.",
        "放射科表示，AI 预分诊工具有助于优先处理急重症影像并提升整体通量。",
        "2026-04-08",
    ),
    _build_article(
        "seed-health-002",
        "bio-innovation",
        "mRNA manufacturing lines expand to support personalized vaccine trials",
        "mRNA 产线扩容以支持个性化疫苗试验",
        "Biotech groups are investing in flexible production modules for smaller and faster clinical batches.",
        "多家生物技术企业正在投资更灵活的生产模块，以满足更小批量、更快节奏的临床试验需求。",
        "2026-04-09",
    ),
    _build_article(
        "seed-health-003",
        "health-next",
        "Wearable glucose sensors improve adherence among chronic-care patients",
        "可穿戴葡萄糖传感器提升慢病患者依从性",
        "Clinics reported better follow-up rates after combining continuous sensing with mobile reminders.",
        "门诊反馈显示，连续监测结合移动提醒后，患者复诊率与管理依从性有所改善。",
        "2026-04-10",
    ),
    _build_article(
        "seed-health-004",
        "bio-innovation",
        "Telehealth reimbursement talks shape the next phase of digital care",
        "远程医疗支付谈判影响数字医疗下一阶段扩张",
        "Providers said reimbursement uncertainty remains the biggest variable for remote-care investment plans.",
        "服务提供方认为，支付政策的不确定性仍是远程医疗投资计划中的最大变量。",
        "2026-04-11",
    ),
    _build_article(
        "seed-finance-001",
        "capital-pulse",
        "Digital banks cut approval time for small business credit lines",
        "数字银行缩短中小企业授信审批时间",
        "Lenders said better risk models are allowing faster decisions without widening default exposure.",
        "放贷机构表示，更成熟的风控模型让审批速度提升，同时没有明显放大违约风险。",
        "2026-04-08",
    ),
    _build_article(
        "seed-finance-002",
        "fintech-scope",
        "Payment processors launch faster cross-border settlement rails",
        "支付机构上线更快的跨境结算通道",
        "New settlement networks are promising lower friction for exporters and regional service platforms.",
        "新的清结算网络有望降低出口商与区域服务平台的跨境收款摩擦。",
        "2026-04-09",
    ),
    _build_article(
        "seed-finance-003",
        "capital-pulse",
        "AI compliance copilots help brokers review large policy updates",
        "AI 合规助手帮助券商处理大规模政策更新",
        "Brokerage teams said automated comparison tools are reducing manual review load during regulatory change cycles.",
        "券商团队表示，自动比对工具正在降低监管规则变动周期中的人工审阅压力。",
        "2026-04-10",
    ),
    _build_article(
        "seed-finance-004",
        "fintech-scope",
        "Tokenized bond settlement pilots draw interest from regional exchanges",
        "代币化债券结算试点吸引区域交易所关注",
        "Market operators are testing programmable settlement steps to improve transparency and shorten back-office cycles.",
        "市场运营方正在测试可编程结算流程，以提升透明度并缩短后台处理周期。",
        "2026-04-11",
    ),
    _build_article(
        "seed-culture-001",
        "travel-loop",
        "Concert tourism lifts hotel bookings across second-tier cities",
        "演唱会旅游带动二线城市酒店预订增长",
        "Travel agencies said music events are extending weekend stays and raising local consumption.",
        "旅行机构表示，音乐活动正在拉长周末停留时间，并带动本地消费提升。",
        "2026-04-08",
    ),
    _build_article(
        "seed-culture-002",
        "culture-grid",
        "Museums deploy AR guides to attract family visitors",
        "博物馆上线 AR 导览吸引亲子客群",
        "Cultural venues said interactive overlays are improving dwell time and repeat visits among younger families.",
        "文化场馆称，增强现实导览提升了亲子用户的停留时长与复访意愿。",
        "2026-04-09",
    ),
    _build_article(
        "seed-culture-003",
        "travel-loop",
        "Short-video creators help scenic towns build spring travel buzz",
        "短视频创作者带动小城春季旅游热度",
        "Local tourism boards are working with creators to package routes, food scenes, and event calendars.",
        "多地文旅部门正与创作者合作，组合线路、美食与活动日历，提升目的地传播效率。",
        "2026-04-10",
    ),
    _build_article(
        "seed-culture-004",
        "culture-grid",
        "Theme parks test dynamic pricing around holiday demand peaks",
        "主题乐园试行节假日动态票价机制",
        "Operators said new pricing tools may improve attendance management but could trigger public sensitivity.",
        "运营方表示，动态票价有助于调节客流，但也可能引发游客对价格波动的敏感反应。",
        "2026-04-11",
    ),
    _build_article(
        "seed-ai-005",
        "silicon-dispatch",
        "Advanced packaging suppliers add capacity for AI accelerator modules",
        "先进封装供应商为 AI 加速模块扩充产能",
        "Packaging and interconnect upgrades are supporting stronger delivery confidence for accelerator racks.",
        "先进封装与互连升级正在提升 AI 加速机柜的交付把握。",
        "2026-04-12",
    ),
    _build_article(
        "seed-ai-006",
        "silicon-dispatch",
        "Private inference appliances win pilot orders from manufacturing groups",
        "私有推理一体机获得制造业客户试点订单",
        "Vendors said factory buyers want compact AI systems that keep latency low and data on site.",
        "厂商表示，制造业客户更看重低时延、数据本地留存的紧凑型 AI 系统。",
        "2026-04-13",
    ),
    _build_article(
        "seed-ev-005",
        "mobility-journal",
        "Apartment districts accelerate curbside charger rollout for shared EVs",
        "居民社区加快共享电动车路侧充电桩铺设",
        "City pilots said overnight curbside charging improves vehicle turnover in dense apartment districts.",
        "多地试点显示，夜间路侧充电正在改善高密度社区共享车辆的周转效率。",
        "2026-04-12",
    ),
    _build_article(
        "seed-ev-006",
        "mobility-journal",
        "Battery health analytics help taxi fleets plan pack replacement cycles",
        "电池健康分析帮助出租车车队规划换包周期",
        "Fleet managers said better diagnostics reduce sudden downtime and make maintenance plans more efficient.",
        "车队管理方表示，更准确的诊断可以减少突发停运，并让维护安排更高效。",
        "2026-04-13",
    ),
    _build_article(
        "seed-sport-005",
        "fan-route",
        "Clubs expand premium hospitality around derby weekends",
        "俱乐部在德比赛事周末扩展高端观赛接待服务",
        "Operators said bundled hospitality products are creating stronger matchday revenue momentum.",
        "运营方表示，打包式接待产品正在带来更强的比赛日收入增长势头。",
        "2026-04-12",
    ),
    _build_article(
        "seed-sport-006",
        "fan-route",
        "Mobile ticketing pilots cut queue pressure outside tournament venues",
        "移动票务试点缓解大型赛事场馆外排队压力",
        "Event teams reported faster entry speed after routing more fans through mobile validation lanes.",
        "赛事团队表示，将更多观众导入移动验票通道后，入场速度明显提升。",
        "2026-04-13",
    ),
    _build_article(
        "seed-energy-005",
        "power-market",
        "Demand-response aggregators ease evening stress on urban grids",
        "需求响应聚合商缓解城市电网晚高峰压力",
        "Utilities said flexible industrial loads are helping smooth evening demand spikes at lower cost.",
        "公用事业方表示，灵活工业负荷正在以更低成本帮助平滑晚高峰负载。",
        "2026-04-12",
    ),
    _build_article(
        "seed-energy-006",
        "power-market",
        "Transmission bottlenecks delay solar delivery from western energy bases",
        "输电瓶颈拖慢西部能源基地光伏外送",
        "Developers warned that line congestion and maintenance windows are putting pressure on solar delivery schedules.",
        "开发商警告称，线路拥堵与检修窗口正在给光伏外送计划带来压力。",
        "2026-04-13",
    ),
    _build_article(
        "seed-security-005",
        "threat-monitor",
        "Banks adopt passkey login programs to reduce credential theft",
        "银行启动通行密钥登录计划以减少凭证盗用",
        "Security teams said passkey rollouts help lower phishing exposure across retail banking portals.",
        "安全团队表示，通行密钥推广有助于降低零售银行入口的钓鱼风险暴露。",
        "2026-04-12",
    ),
    _build_article(
        "seed-security-006",
        "threat-monitor",
        "Managed detection teams warn of supplier portal intrusion drills",
        "托管检测团队警惕供应商门户入侵演练升级",
        "Researchers said weak supplier access reviews remain a serious risk for enterprise collaboration systems.",
        "研究人员指出，供应商访问审查不足仍是企业协同系统面临的严重风险。",
        "2026-04-13",
    ),
    _build_article(
        "seed-health-005",
        "med-device",
        "County hospitals add surgical robot tenders to equipment budgets",
        "县域医院将手术机器人招标纳入设备预算",
        "Procurement teams said robotic surgery platforms are moving from showcase projects into regular planning cycles.",
        "采购团队表示，手术机器人平台正从展示性项目走向常规预算周期。",
        "2026-04-12",
    ),
    _build_article(
        "seed-health-006",
        "med-device",
        "Home-care kits pair remote vitals devices with nurse follow-up",
        "居家护理套件把远程生命体征设备与护士随访结合",
        "Providers reported better chronic-care follow-up after linking home devices with coordinated nurse outreach.",
        "服务机构反馈，将家庭监测设备与护士协同随访结合后，慢病跟进效果更稳定。",
        "2026-04-13",
    ),
    _build_article(
        "seed-finance-005",
        "payments-wire",
        "Merchant acquirers use AI fraud scoring to cut chargeback losses",
        "收单机构利用 AI 风险评分压降拒付损失",
        "Payments teams said better fraud scoring is helping merchants keep approval rates high without inviting extra risk.",
        "支付团队表示，更好的欺诈评分正在帮助商户在不放大风险的前提下维持较高通过率。",
        "2026-04-12",
    ),
    _build_article(
        "seed-finance-006",
        "payments-wire",
        "Treasury apps bundle instant settlement with invoice financing",
        "资金管理应用把即时结算与发票融资打包提供",
        "Fintech operators said small exporters want fewer workflow steps between settlement and short-term credit.",
        "金融科技平台表示，中小外贸企业希望缩短结算与短期融资之间的流程链路。",
        "2026-04-13",
    ),
    _build_article(
        "seed-culture-005",
        "exhibit-lab",
        "Immersive exhibitions extend museum evening attendance",
        "沉浸式展陈延长博物馆夜场停留时间",
        "Curators said projection-driven exhibits are drawing more evening visitors and boosting repeat trips.",
        "策展团队表示，以投影互动为核心的展陈正在吸引更多夜场客流，并提高复访意愿。",
        "2026-04-12",
    ),
    _build_article(
        "seed-culture-006",
        "exhibit-lab",
        "County cultural routes bundle performances, markets and lodging",
        "县域文旅线路把演出、集市与住宿打包联动",
        "Local planners said integrated route packages are helping visitors stay longer and spend more broadly.",
        "地方策划方表示，一体化线路套餐正在帮助游客停留更久，并带动更广泛消费。",
        "2026-04-13",
    ),
]


EXTRA_SEED_ARTICLE_SPECS = [
    (
        "seed-sport-007",
        "hupu-nba",
        "Hupu notes a strong fourth-quarter win keeps the playoff push alive",
        "虎扑关注强势第四节胜利让球队继续保有季后赛希望",
        "A strong finish and confident guard play helped the team secure a win and rebuild momentum after a tense road trip.",
        "球队靠末节发力和后卫线的自信表现拿下胜利，在紧张客场之旅后重新提振士气。",
        "2026-03-18",
    ),
    (
        "seed-sport-008",
        "nba-official",
        "NBA report says a starting guard is out two weeks with an ankle injury",
        "NBA官网通报首发后卫因脚踝伤势缺席两周",
        "Medical staff warned that the ankle injury creates pressure on rotation depth before a difficult back-to-back stretch.",
        "医疗团队表示，这次脚踝伤病会让球队在连续比赛前面临更大的轮换压力。",
        "2026-03-22",
    ),
    (
        "seed-sport-009",
        "hupu-nba",
        "Bench rebound helps the western contender snap a two-game loss",
        "替补阵容反弹帮助西部劲旅止住两连败",
        "Fans celebrated the rebound after reserve scorers delivered a thrilling win and restored healthy momentum.",
        "替补得分点带来的精彩胜利引发球迷庆祝，也让球队重新找回积极势头。",
        "2026-03-27",
    ),
    (
        "seed-sport-010",
        "nba-official",
        "Veteran center returned from calf strain and lifted the team to victory",
        "老将中锋从小腿拉伤中复出并帮助球队取胜",
        "Coaches said the veteran returned in strong condition and his recovery improved rim protection in the victory.",
        "教练组表示，这位老将以良好状态复出，他的恢复明显提升了球队在胜利中的护框质量。",
        "2026-04-01",
    ),
    (
        "seed-sport-011",
        "hupu-nba",
        "Late collapse hands the contender another loss and raises pressure",
        "末节崩盘让争冠球队再吞失利并加剧压力",
        "Supporters grew cautious after a weak closing stretch turned a likely win into a painful loss with more pressure on the coach.",
        "最后时刻表现疲软把原本接近到手的胜利变成失利，球迷态度转为谨慎，主教练压力也继续上升。",
        "2026-04-04",
    ),
    (
        "seed-sport-012",
        "nba-official",
        "Forward recovery stays on schedule before a possible April return",
        "前锋恢复进度正常有望在四月复出",
        "The club said the forward recovery remains strong, though officials stay cautious about contact work this week.",
        "球队表示这名前锋恢复情况良好，不过本周对抗训练安排仍会保持谨慎。",
        "2026-04-07",
    ),
    (
        "seed-ai-007",
        "openai-watch",
        "Agent pilots show strong adoption in customer support teams",
        "智能体试点在客服团队中展现出强劲采用势头",
        "Managers said the agent rollout improved response quality, lowered queue pressure, and produced a healthy satisfaction rebound.",
        "管理者表示，智能体上线改善了回复质量、降低了排队压力，并带来了满意度回升。",
        "2026-03-19",
    ),
    (
        "seed-ai-008",
        "model-wire",
        "GPU shortage slows multimodal model rollout at several cloud vendors",
        "GPU短缺拖慢多家云厂商多模态模型上线节奏",
        "Executives warned that the GPU shortage and delivery delays are creating uncertainty for spring model launches.",
        "高管警告称，GPU短缺和交付延迟正在给春季模型上线带来不确定性。",
        "2026-03-24",
    ),
    (
        "seed-ai-009",
        "infra-radar",
        "Reasoning benchmark improved while inference costs moved lower",
        "推理基准成绩提升同时推理成本继续走低",
        "Infrastructure teams said a new reasoning stack improved coding accuracy and delivered a faster, lower-cost serving profile.",
        "基础设施团队表示，新推理栈提升了代码任务准确率，并带来了更快、更低成本的服务表现。",
        "2026-03-29",
    ),
    (
        "seed-ai-010",
        "openai-watch",
        "Safety review delays a voice agent launch in Europe",
        "安全审查推迟语音智能体在欧洲的上线",
        "Product leads said the delay is serious enough to create pressure on partner schedules even as trust requirements stay important.",
        "产品负责人表示，这次延期已经对合作方排期造成明显压力，但安全与可信要求依然重要。",
        "2026-04-02",
    ),
    (
        "seed-ai-011",
        "model-wire",
        "Enterprise buyers expand AI appliance orders after a strong demo cycle",
        "企业客户在一轮强势演示后扩大AI一体机订单",
        "Vendors said strong pilot feedback and reliable deployment tools are supporting a fresh round of appliance growth.",
        "厂商表示，试点反馈积极，加上部署工具更可靠，正在支撑新一轮一体机需求增长。",
        "2026-04-05",
    ),
    (
        "seed-ai-012",
        "infra-radar",
        "Chip packaging bottleneck creates uncertainty for April accelerator delivery",
        "芯片封装瓶颈让四月加速卡交付出现不确定性",
        "System builders warned that a packaging bottleneck could slow accelerator delivery and keep procurement teams cautious.",
        "系统集成商警告称，封装瓶颈可能拖慢加速卡交付，并让采购团队继续保持谨慎。",
        "2026-04-07",
    ),
    (
        "seed-finance-007",
        "market-expectations",
        "Analysts expect a bank earnings beat to lift financial shares after March rebound",
        "分析师预计银行业绩超预期将推动金融股延续三月反弹",
        "Broker desks said optimistic earnings expectations and stronger capital returns could boost large bank shares again.",
        "券商研究团队表示，乐观的业绩预期与更强的资本回报可能再次提振大型银行股。",
        "2026-03-17",
    ),
    (
        "seed-finance-008",
        "forex-flash",
        "Dollar strength puts pressure on Asian importers as hedging costs climb",
        "美元走强叠加套保成本上升令亚洲进口商承压",
        "Treasury desks said currency pressure and more expensive hedging are making buyers cautious ahead of the next rate meeting.",
        "外汇交易台表示，汇率压力与更高的套保成本正使买方在下次利率会议前保持谨慎。",
        "2026-03-23",
    ),
    (
        "seed-finance-009",
        "equity-sentiment",
        "Chip stock rally gains support after analysts upgrade demand forecasts",
        "分析师上调需求预期后芯片股反弹获得更多支撑",
        "Fund managers said the rally looks stronger after several upgrades and a healthier outlook for second-quarter orders.",
        "基金经理表示，在多份上调评级与更健康的二季度订单展望推动下，这轮反弹显得更强。",
        "2026-03-28",
    ),
    (
        "seed-finance-010",
        "market-expectations",
        "Retail shares slip after cautious guidance and slower store traffic",
        "零售股因谨慎指引和门店客流放缓而走弱",
        "Investors said cautious guidance, slower traffic, and margin pressure are keeping expectations soft for the sector.",
        "投资者表示，谨慎的业绩指引、放缓的客流与利润压力让板块预期持续偏弱。",
        "2026-04-01",
    ),
    (
        "seed-finance-011",
        "forex-flash",
        "Exporters welcome lower yen volatility as hedge costs improve",
        "日元波动收敛并降低套保成本令出口商情绪改善",
        "Currency strategists said lower volatility and improved hedge pricing are supporting a more optimistic export outlook.",
        "外汇策略师表示，更低的波动率和改善的套保报价正在支撑更乐观的出口前景。",
        "2026-04-04",
    ),
    (
        "seed-finance-012",
        "equity-sentiment",
        "Property stocks face a fresh selloff as refinancing risk grows",
        "地产股因再融资风险升温再遭抛售",
        "Portfolio managers warned that a fresh selloff and rising refinancing risk could keep the sector under pressure into April.",
        "投资组合经理警告称，新一轮抛售与再融资风险升温可能让地产板块在四月继续承压。",
        "2026-04-07",
    ),
]

SEED_ARTICLES.extend(_build_article(*spec) for spec in EXTRA_SEED_ARTICLE_SPECS)


FOLLOWUP_ARTICLES = [
    _build_article(
        "follow-ai-001",
        "compute-frontier",
        "Cloud buyers sign fresh inference contracts for regional AI campuses",
        "区域 AI 园区拿下新一轮推理算力合同",
        "Operators said enterprise demand remains healthy for inference servers and memory upgrades.",
        "运营方表示，企业客户对推理服务器与内存升级的需求仍然稳健。",
        "2026-04-14",
    ),
    _build_article(
        "follow-ai-002",
        "ai-systems-weekly",
        "Cooling delays create pressure on part of the AI server expansion cycle",
        "冷却设备延期给部分 AI 服务器扩产计划带来压力",
        "Integrators warned that cooling equipment bottlenecks could slow some delivery milestones.",
        "系统集成商警告称，冷却设备瓶颈可能拖慢部分项目的交付节点。",
        "2026-04-15",
    ),
    _build_article(
        "follow-ai-003",
        "compute-frontier",
        "Edge inference modules attract public-sector procurement interest",
        "边缘推理模块吸引公共部门采购关注",
        "Compact AI systems are winning attention where power budgets and latency targets are strict.",
        "在电力预算和时延要求更严格的场景中，轻量化 AI 系统正在获得更多关注。",
        "2026-04-16",
    ),
    _build_article(
        "follow-ev-001",
        "ev-insight",
        "Battery leasing models support electric van rollouts for urban fleets",
        "电池租赁模式推动城市物流车队加快电动化",
        "Fleet buyers said leasing lowers upfront risk and keeps renewal plans more flexible.",
        "车队采购方表示，电池租赁能降低前期投入风险，并提高更新计划灵活性。",
        "2026-04-14",
    ),
    _build_article(
        "follow-ev-002",
        "charge-network",
        "Recycled cathode pilots help stabilize mainstream EV pack costs",
        "再生正极材料试点有助于稳定主流电动车电池成本",
        "Manufacturers reported encouraging yield rates as recycling supply chains mature.",
        "制造商称，随着回收链条成熟，再生材料试点的良率表现令人鼓舞。",
        "2026-04-15",
    ),
    _build_article(
        "follow-ev-003",
        "ev-insight",
        "Charging hardware shortages slow parts of the intercity rollout plan",
        "充电设备短缺拖慢部分城际站点建设进度",
        "Developers said hardware bottlenecks and permit delays are still weighing on project delivery.",
        "开发方表示，设备短缺与审批延迟仍在影响项目交付节奏。",
        "2026-04-16",
    ),
    _build_article(
        "follow-sport-001",
        "pitch-report",
        "League leaders salvage a draw before a decisive continental quarterfinal",
        "联赛领头羊在洲际淘汰赛前艰难抢下一场平局",
        "Supporters stayed optimistic after a resilient finish preserved momentum for the bigger tie ahead.",
        "球队在比赛末段顽强追平后，球迷对即将到来的关键战保持乐观。",
        "2026-04-14",
    ),
    _build_article(
        "follow-sport-002",
        "stadium-wire",
        "Host city releases fan-routing plans for a summer football festival",
        "主办城市公布夏季足球嘉年华观赛动线方案",
        "Officials said transport upgrades should cut bottlenecks around the main venue district.",
        "官方表示，新的交通组织方案将缓解主场馆片区的拥堵瓶颈。",
        "2026-04-15",
    ),
    _build_article(
        "follow-sport-003",
        "pitch-report",
        "Training injury clouds the semifinal plan for a cup contender",
        "训练伤病为杯赛热门球队的半决赛部署蒙上阴影",
        "Medical staff said one setback could alter rotation choices ahead of the knockout tie.",
        "医疗团队指出，关键球员的伤情可能迫使教练组重新调整轮换方案。",
        "2026-04-16",
    ),
    _build_article(
        "follow-energy-001",
        "climate-desk",
        "Heat resilience plans drive fresh solar-and-storage bids in city districts",
        "城市高温韧性计划带动新一轮光储项目招标",
        "Local governments are accelerating distributed energy projects for cooling and backup power.",
        "多地政府正在加速推进面向制冷与备用电源的分布式能源项目。",
        "2026-04-14",
    ),
    _build_article(
        "follow-energy-002",
        "grid-watch",
        "Wind developers renegotiate timelines as permitting drag persists",
        "风电开发商在审批拖延下重新谈判项目时程",
        "Developers warned that paperwork delays are adding new uncertainty to financing calendars.",
        "开发商警告称，审批文书拖延正在给融资时间表带来新的不确定性。",
        "2026-04-15",
    ),
    _build_article(
        "follow-energy-003",
        "climate-desk",
        "Hydro shortfall keeps electricity traders cautious before summer demand",
        "水电缺口让交易员在夏季需求来临前保持谨慎",
        "Dry conditions are raising concerns about tighter power markets in the coming weeks.",
        "持续偏干天气正加剧市场对未来数周电力供应偏紧的担忧。",
        "2026-04-16",
    ),
    _build_article(
        "follow-security-001",
        "cyber-brief",
        "Identity governance platforms gain budget priority after recent audit failures",
        "近期审计失分后，身份治理平台预算优先级上升",
        "Boards are asking security teams to strengthen access reviews and privileged account visibility.",
        "董事会正在要求安全团队强化权限审查与高权限账号可视化能力。",
        "2026-04-14",
    ),
    _build_article(
        "follow-security-002",
        "security-post",
        "Healthcare vendors rush to patch exposed remote management tools",
        "医疗软件供应商紧急修补暴露的远程运维入口",
        "Researchers said weak segmentation and shared admin accounts remain major risk factors.",
        "研究人员指出，隔离不足与共享管理员账号仍是主要风险因素。",
        "2026-04-15",
    ),
    _build_article(
        "follow-security-003",
        "cyber-brief",
        "Breach disclosure deadlines pressure firms to automate evidence collection",
        "披露时限收紧倒逼企业自动化留痕取证流程",
        "Compliance teams are adopting faster evidence pipelines to keep up with regulator expectations.",
        "合规团队正在部署更快的证据收集流程，以满足监管方更高的时效要求。",
        "2026-04-16",
    ),
    _build_article(
        "follow-health-001",
        "health-next",
        "Hospital imaging departments expand AI triage after shorter wait times",
        "候诊时间缩短后，医院影像科扩大 AI 预分诊范围",
        "Departments said automated prioritization is helping manage heavy scan backlogs more predictably.",
        "科室表示，自动优先级排序正在帮助他们更稳定地处理大量待阅影像。",
        "2026-04-14",
    ),
    _build_article(
        "follow-health-002",
        "bio-innovation",
        "Personalized vaccine programs gain new manufacturing capacity",
        "个性化疫苗项目获得新的产能支持",
        "Flexible manufacturing modules are helping small-batch biologics move faster into trials.",
        "柔性生产模块正在帮助小批量生物制品更快进入临床试验阶段。",
        "2026-04-15",
    ),
    _build_article(
        "follow-health-003",
        "health-next",
        "Telehealth payment uncertainty slows remote chronic-care investment",
        "远程慢病管理投资因支付不确定性而放缓",
        "Providers said financing decisions remain cautious until reimbursement clarity improves.",
        "服务机构表示，在支付政策更明确之前，相关投资决策仍将保持谨慎。",
        "2026-04-16",
    ),
    _build_article(
        "follow-finance-001",
        "capital-pulse",
        "Digital lenders use newer risk models to widen SME credit access",
        "数字放贷机构借助新风控模型扩大中小企业授信覆盖",
        "Banks said better signals are helping them approve qualified borrowers faster.",
        "银行表示，更丰富的风险信号正在帮助他们更快通过合格借款人的申请。",
        "2026-04-14",
    ),
    _build_article(
        "follow-finance-002",
        "fintech-scope",
        "Cross-border payment rails attract exporters looking for faster settlement",
        "更快的跨境支付通道吸引外贸企业试用",
        "Merchants said shorter settlement cycles are improving cash flow visibility.",
        "商户表示，更短的清算周期正在改善资金回笼的可预期性。",
        "2026-04-15",
    ),
    _build_article(
        "follow-finance-003",
        "capital-pulse",
        "Compliance copilots face scrutiny over hallucinated policy summaries",
        "合规助手因政策摘要幻觉问题面临审查",
        "Risk teams warned that automated summaries still need strong human review before use.",
        "风控团队警告称，自动摘要在正式使用前仍需要严格的人工复核。",
        "2026-04-16",
    ),
    _build_article(
        "follow-culture-001",
        "travel-loop",
        "Festival weekends keep second-tier city hotel bookings elevated",
        "节庆周末持续抬升二线城市酒店预订热度",
        "Travel platforms said event-driven stays remain one of the strongest leisure booking drivers.",
        "旅游平台表示，活动驱动型停留仍是休闲预订增长最明显的动力之一。",
        "2026-04-14",
    ),
    _build_article(
        "follow-culture-002",
        "culture-grid",
        "Museums refine AR content after strong family adoption in spring",
        "春季亲子客群增长后，博物馆继续优化 AR 导览内容",
        "Curators said interactive exhibits are increasing repeat visits and longer on-site stays.",
        "策展团队表示，互动展项正在提高复访率，并延长用户现场停留时间。",
        "2026-04-15",
    ),
    _build_article(
        "follow-culture-003",
        "travel-loop",
        "Dynamic theme-park pricing triggers debate over holiday affordability",
        "主题乐园动态票价引发节假日可负担性讨论",
        "Consumers said flexible pricing can smooth crowds, but sudden surges remain sensitive.",
        "消费者认为，灵活票价有助于分散客流，但节假日价格突升仍然敏感。",
        "2026-04-16",
    ),
    _build_article(
        "follow-ai-004",
        "silicon-dispatch",
        "Optical interconnect demand rises as AI rack density improves",
        "随着 AI 机柜密度提升，光互连需求继续走高",
        "Suppliers said denser accelerator clusters are supporting fresh upgrades in optical links and packaging.",
        "供应商表示，更高密度的 AI 集群正在带动光互连与封装链路的新一轮升级。",
        "2026-04-14",
    ),
    _build_article(
        "follow-ai-005",
        "silicon-dispatch",
        "Advanced packaging lead times remain tight for some accelerator orders",
        "部分加速卡订单仍受先进封装交期偏紧影响",
        "Integrators warned that packaging capacity remains a bottleneck for a portion of high-end accelerator deliveries.",
        "系统集成商警告称，先进封装产能仍是部分高端加速卡交付中的瓶颈。",
        "2026-04-15",
    ),
    _build_article(
        "follow-ev-004",
        "mobility-journal",
        "Neighborhood charging pilots improve overnight EV utilization",
        "社区充电试点提升夜间电动车利用率",
        "Operators reported healthier overnight charging patterns after adding curbside stations near housing clusters.",
        "运营方反馈，在居民区附近补充路侧站点后，夜间充电利用率明显改善。",
        "2026-04-14",
    ),
    _build_article(
        "follow-ev-005",
        "mobility-journal",
        "Fleet battery diagnostics expose replacement pressure on high-mileage vans",
        "车队电池诊断暴露高里程厢式车换包压力",
        "Fleet managers warned that intensive urban routes are creating earlier battery replacement pressure than expected.",
        "车队管理方警告称，高强度城市线路正在让部分车辆更早面临换包压力。",
        "2026-04-15",
    ),
    _build_article(
        "follow-sport-004",
        "fan-route",
        "Hospitality packages boost derby-day revenue for clubs",
        "观赛接待套餐带动俱乐部德比赛日收入增长",
        "Commercial teams said premium seating bundles are becoming a dependable revenue lever for major fixtures.",
        "商务团队表示，高端座席套餐正在成为关键赛事中更稳定的收入杠杆。",
        "2026-04-14",
    ),
    _build_article(
        "follow-sport-005",
        "fan-route",
        "Security drills expand around festival football venues after crowd concerns",
        "因人流压力上升，足球嘉年华场馆周边安保演练升级",
        "Organizers said crowd-flow concerns are pushing more serious security rehearsals around fan zones.",
        "组织方表示，人流管理担忧正推动球迷活动区周边进行更严密的安保演练。",
        "2026-04-15",
    ),
    _build_article(
        "follow-energy-004",
        "power-market",
        "Demand-response contracts help utilities avoid costly evening spikes",
        "需求响应合约帮助电力公司避开高成本晚高峰波动",
        "Utilities said flexible load contracts are smoothing peak demand and improving grid resilience.",
        "电力公司表示，灵活负荷合约正在平滑峰值需求并增强电网韧性。",
        "2026-04-14",
    ),
    _build_article(
        "follow-energy-005",
        "power-market",
        "Transmission maintenance delays keep some solar output constrained",
        "输电检修延误继续限制部分光伏出力释放",
        "Developers warned that line maintenance delays are adding fresh uncertainty to solar delivery plans.",
        "开发商警告称，输电线路检修延误正在给光伏外送计划带来新的不确定性。",
        "2026-04-15",
    ),
    _build_article(
        "follow-security-004",
        "threat-monitor",
        "Passkey migrations reduce phishing exposure in retail banking portals",
        "通行密钥迁移降低零售银行入口的钓鱼暴露面",
        "Security teams said passkey adoption is helping reduce successful phishing attempts against customer logins.",
        "安全团队表示，通行密钥采用正在减少针对客户登录入口的钓鱼得手率。",
        "2026-04-14",
    ),
    _build_article(
        "follow-security-005",
        "threat-monitor",
        "Supplier access reviews intensify after remote admin breach alarms",
        "远程管理告警出现后，企业加紧审查供应商访问权限",
        "Investigators warned that shared remote admin paths remain a weak point in many supplier ecosystems.",
        "调查人员警告称，共享远程管理通道仍是许多供应商生态中的薄弱点。",
        "2026-04-15",
    ),
    _build_article(
        "follow-health-004",
        "med-device",
        "Surgical robot training centers expand to support hospital adoption",
        "手术机器人培训中心扩容以支撑医院落地应用",
        "Hospital networks said better training capacity is reducing onboarding friction for new surgical systems.",
        "医院网络表示，更完善的培训能力正在降低新型手术系统落地时的摩擦成本。",
        "2026-04-14",
    ),
    _build_article(
        "follow-health-005",
        "med-device",
        "Remote care kit pilots improve follow-up among heart-failure patients",
        "远程护理套件试点提升心衰患者随访效果",
        "Care teams said coordinated device alerts and nurse calls are helping patients stay on treatment plans.",
        "护理团队表示，设备告警与护士回访联动后，患者更容易维持治疗计划。",
        "2026-04-15",
    ),
    _build_article(
        "follow-finance-004",
        "payments-wire",
        "Chargeback analytics platforms gain adoption among cross-border merchants",
        "拒付分析平台在跨境商户中加快普及",
        "Merchants said better fraud analytics are improving approval quality and reducing serious disputes.",
        "商户表示，更好的欺诈分析正在提升交易通过质量并减少严重争议。",
        "2026-04-14",
    ),
    _build_article(
        "follow-finance-005",
        "payments-wire",
        "Instant settlement demand rises among invoice-finance users",
        "发票融资用户对即时结算的需求持续升高",
        "Service providers said faster settlement is becoming important for small firms managing tight cash cycles.",
        "服务机构表示，对现金流周期紧张的小企业而言，更快结算正变得愈发重要。",
        "2026-04-15",
    ),
    _build_article(
        "follow-culture-004",
        "exhibit-lab",
        "Immersive night exhibitions lift museum member renewals",
        "沉浸式夜展带动博物馆会员续费增长",
        "Operators said stronger evening attendance is creating encouraging renewal momentum among members.",
        "运营方表示，更强的夜场到访正在形成积极的会员续费势头。",
        "2026-04-14",
    ),
    _build_article(
        "follow-culture-005",
        "exhibit-lab",
        "Cultural route packages help county festivals spread visitor traffic",
        "文旅线路套餐帮助县域节庆活动分散客流",
        "Planners said bundled routes are improving crowd distribution and keeping local tourism growth healthy.",
        "策划方表示，打包线路正在改善客流分布，并让地方旅游增长保持稳健。",
        "2026-04-15",
    ),
]


EXTRA_FOLLOWUP_ARTICLE_SPECS = [
    (
        "follow-sport-006",
        "hupu-nba",
        "Overtime win keeps the play-in chase alive for a rising roster",
        "加时胜利让上升期阵容继续保有附加赛希望",
        "Fans said the overtime victory showed strong composure and gave the young roster another momentum boost.",
        "球迷认为，这场加时胜利展现了球队的韧性，也再次提振了年轻阵容的士气。",
        "2026-04-14",
    ),
    (
        "follow-sport-007",
        "nba-official",
        "Veteran wing cleared to return after a knee injury recovery",
        "老将侧翼在膝伤恢复后获准复出",
        "The official update said the wing returned to full practice and his recovery should improve perimeter defense immediately.",
        "官方更新称，这名侧翼已恢复完整训练，他的复出有望立即改善球队外线防守。",
        "2026-04-15",
    ),
    (
        "follow-sport-008",
        "hupu-nba",
        "Hamstring injury creates pressure on the rotation before a road trip",
        "腿筋伤势让球队在客场之旅前面临轮换压力",
        "Coaches warned that the injury and short recovery window could leave the guard rotation thin for several games.",
        "教练组警告称，这次伤病叠加短暂恢复窗口，可能让后场轮换在数场比赛中都比较吃紧。",
        "2026-04-16",
    ),
    (
        "follow-sport-009",
        "nba-official",
        "Young guard beats the buzzer in a thrilling comeback victory",
        "年轻后卫压哨绝杀帮助球队完成精彩逆转",
        "Players celebrated the thrilling win after the guard beat the buzzer and lifted confidence around the locker room.",
        "年轻后卫完成压哨绝杀后，全队为这场精彩胜利而庆祝，更衣室气氛也明显转强。",
        "2026-04-17",
    ),
    (
        "follow-sport-010",
        "hupu-nba",
        "A defensive slump leads to a third straight loss and cautious mood",
        "防守低迷导致球队遭遇三连败并使氛围转向谨慎",
        "Supporters said the weak defensive stretch and another loss are increasing pressure on late-season adjustments.",
        "球迷表示，防守端持续低迷和连续失利正在让赛季末段调整面临更大压力。",
        "2026-04-18",
    ),
    (
        "follow-sport-011",
        "nba-official",
        "Reserve center recovery improves and practice workload expands",
        "替补中锋恢复情况改善并扩大训练负荷",
        "Training staff said the center recovery is progressing well and a return could support the second unit soon.",
        "训练团队表示，这名中锋的恢复进展顺利，近期复出后有望增强替补阵容。",
        "2026-04-18",
    ),
    (
        "follow-ai-006",
        "openai-watch",
        "Open model assistants gain strong adoption in April support pilots",
        "开放模型助手在四月客服试点中获得强劲采用",
        "Operations leaders said strong adoption and faster triage are improving response quality across support desks.",
        "运营负责人表示，较高的采用率和更快的分流能力，正在整体提升客服团队的响应质量。",
        "2026-04-14",
    ),
    (
        "follow-ai-007",
        "model-wire",
        "Cooling recovery helps AI server projects rebound after a slow quarter",
        "冷却设备恢复交付帮助AI服务器项目在慢季度后反弹",
        "Suppliers said cooling recovery and lower installation delays are helping large AI server projects rebound.",
        "供应商表示，冷却设备交付恢复以及更少的安装延迟，正在帮助大型AI服务器项目重新反弹。",
        "2026-04-15",
    ),
    (
        "follow-ai-008",
        "infra-radar",
        "Benchmark miss puts pressure on a small-model startup valuation",
        "基准测试失利给小模型创业公司估值带来压力",
        "Investors warned that a benchmark miss and uncertain commercial traction could keep the valuation under pressure.",
        "投资人警告称，基准测试失利和商业化前景不确定可能让这家公司的估值持续承压。",
        "2026-04-16",
    ),
    (
        "follow-ai-009",
        "openai-watch",
        "Agent tooling upgrade improves latency for enterprise developers",
        "智能体工具链升级改善企业开发者的延迟体验",
        "Product teams said the tooling upgrade improved latency, reduced setup friction, and delivered a more reliable workflow.",
        "产品团队表示，这次工具链升级改善了延迟、降低了接入摩擦，并提供了更可靠的工作流。",
        "2026-04-17",
    ),
    (
        "follow-ai-010",
        "model-wire",
        "Training budget cuts create a cautious outlook for frontier experiments",
        "训练预算削减让前沿模型实验前景转为谨慎",
        "Research managers said budget cuts and slower hiring are creating pressure on several frontier model experiments.",
        "研究负责人表示，预算削减和招聘放缓正在给多项前沿模型实验带来压力。",
        "2026-04-18",
    ),
    (
        "follow-ai-011",
        "infra-radar",
        "Inference chips win robotics contracts as edge AI demand grows",
        "推理芯片拿下机器人合同并受益于边缘AI需求增长",
        "Chip vendors said the contract win and healthy robotics demand are supporting a strong second-quarter outlook.",
        "芯片厂商表示，新合同的拿下和机器人需求的稳健增长，正在支撑更强的二季度展望。",
        "2026-04-18",
    ),
    (
        "follow-finance-006",
        "market-expectations",
        "Software stocks jump after investors celebrate an earnings beat",
        "投资者庆祝业绩超预期推动软件股走强",
        "Traders said the earnings beat and stronger guidance could boost software shares for another week.",
        "交易员表示，业绩超预期和更强的业绩指引，可能继续提振软件股表现。",
        "2026-04-14",
    ),
    (
        "follow-finance-007",
        "forex-flash",
        "Euro rebound improves margins and reduces pressure on importers",
        "欧元反弹改善利润率并缓解进口商压力",
        "Currency desks said the euro rebound is lowering near-term hedge losses and improving confidence among importers.",
        "外汇交易台表示，欧元反弹正在降低近期套保损失，并改善进口商信心。",
        "2026-04-15",
    ),
    (
        "follow-finance-008",
        "equity-sentiment",
        "Chipmakers tumble after a cautious capital-spending forecast",
        "芯片制造商因谨慎资本开支展望而下挫",
        "Funds said a cautious spending forecast and weaker order visibility triggered another tumble in chip shares.",
        "基金经理表示，谨慎的资本开支展望和偏弱的订单能见度引发了芯片股再度下挫。",
        "2026-04-16",
    ),
    (
        "follow-finance-009",
        "market-expectations",
        "Dividend banks keep support despite rate uncertainty",
        "高股息银行股在利率不确定下仍获支撑",
        "Strategists said healthy dividends and resilient balance sheets continue to support the sector despite rate uncertainty.",
        "策略师表示，尽管利率前景仍不确定，但稳健分红和有韧性的资产负债表仍在支撑该板块。",
        "2026-04-17",
    ),
    (
        "follow-finance-010",
        "forex-flash",
        "Yuan recovery helps airlines lock lower fuel-payment costs",
        "人民币回稳帮助航空公司锁定更低燃油支付成本",
        "Dealers said the yuan recovery and lower payment costs are improving cash-flow expectations for airlines.",
        "交易员表示，人民币回稳和更低的支付成本正在改善航空公司的现金流预期。",
        "2026-04-18",
    ),
    (
        "follow-finance-011",
        "equity-sentiment",
        "Small-cap shares remain under pressure after a weak financing update",
        "小盘股因融资更新偏弱而持续承压",
        "Investors said the weak financing update and another cautious outlook keep small-cap sentiment under pressure.",
        "投资者表示，偏弱的融资更新和再次转谨慎的展望让小盘股情绪持续承压。",
        "2026-04-18",
    ),
]

FOLLOWUP_ARTICLES.extend(_build_article(*spec) for spec in EXTRA_FOLLOWUP_ARTICLE_SPECS)


EXTRA_FOLLOWUP_ARTICLE_SPECS = [
    (
        "follow-sport-006",
        "hupu-nba",
        "Overtime win keeps the play-in chase alive for a rising roster",
        "加时胜利让上升期阵容继续保有附加赛希望",
        "Fans said the overtime victory showed strong composure and gave the young roster another momentum boost.",
        "球迷认为，这场加时胜利展现了球队的韧性，也再次提振了年轻阵容的士气。",
        "2026-04-14",
    ),
    (
        "follow-sport-007",
        "nba-official",
        "Veteran wing cleared to return after a knee injury recovery",
        "老将侧翼在膝伤恢复后获准复出",
        "The official update said the wing returned to full practice and his recovery should improve perimeter defense immediately.",
        "官方更新称，这名侧翼已恢复完整训练，他的复出有望立即改善球队外线防守。",
        "2026-04-15",
    ),
    (
        "follow-sport-008",
        "hupu-nba",
        "Hamstring injury creates pressure on the rotation before a road trip",
        "腿筋伤势让球队在客场之旅前面临轮换压力",
        "Coaches warned that the injury and short recovery window could leave the guard rotation thin for several games.",
        "教练组警告称，这次伤病叠加短暂恢复窗口，可能让后场轮换在数场比赛中都比较吃紧。",
        "2026-04-16",
    ),
    (
        "follow-sport-009",
        "nba-official",
        "Young guard beats the buzzer in a thrilling comeback victory",
        "年轻后卫压哨绝杀帮助球队完成精彩逆转",
        "Players celebrated the thrilling win after the guard beat the buzzer and lifted confidence around the locker room.",
        "年轻后卫完成压哨绝杀后，全队为这场精彩胜利而庆祝，更衣室气氛也明显转强。",
        "2026-04-17",
    ),
    (
        "follow-sport-010",
        "hupu-nba",
        "A defensive slump leads to a third straight loss and cautious mood",
        "防守低迷导致球队遭遇三连败并使氛围转向谨慎",
        "Supporters said the weak defensive stretch and another loss are increasing pressure on late-season adjustments.",
        "球迷表示，防守端持续低迷和连续失利正在让赛季末段调整面临更大压力。",
        "2026-04-18",
    ),
    (
        "follow-sport-011",
        "nba-official",
        "Reserve center recovery improves and practice workload expands",
        "替补中锋恢复情况改善并扩大训练负荷",
        "Training staff said the center recovery is progressing well and a return could support the second unit soon.",
        "训练团队表示，这名中锋的恢复进展顺利，近期复出后有望增强替补阵容。",
        "2026-04-18",
    ),
    (
        "follow-ai-006",
        "openai-watch",
        "Open model assistants gain strong adoption in April support pilots",
        "开放模型助手在四月客服试点中获得强劲采用",
        "Operations leaders said strong adoption and faster triage are improving response quality across support desks.",
        "运营负责人表示，较高的采用率和更快的分流能力，正在整体提升客服团队的响应质量。",
        "2026-04-14",
    ),
    (
        "follow-ai-007",
        "model-wire",
        "Cooling recovery helps AI server projects rebound after a slow quarter",
        "冷却设备恢复交付帮助AI服务器项目在慢季度后反弹",
        "Suppliers said cooling recovery and lower installation delays are helping large AI server projects rebound.",
        "供应商表示，冷却设备交付恢复以及更少的安装延迟，正在帮助大型AI服务器项目重新反弹。",
        "2026-04-15",
    ),
    (
        "follow-ai-008",
        "infra-radar",
        "Benchmark miss puts pressure on a small-model startup valuation",
        "基准测试失利给小模型创业公司估值带来压力",
        "Investors warned that a benchmark miss and uncertain commercial traction could keep the valuation under pressure.",
        "投资人警告称，基准测试失利和商业化前景不确定可能让这家公司的估值持续承压。",
        "2026-04-16",
    ),
    (
        "follow-ai-009",
        "openai-watch",
        "Agent tooling upgrade improves latency for enterprise developers",
        "智能体工具链升级改善企业开发者的延迟体验",
        "Product teams said the tooling upgrade improved latency, reduced setup friction, and delivered a more reliable workflow.",
        "产品团队表示，这次工具链升级改善了延迟、降低了接入摩擦，并提供了更可靠的工作流。",
        "2026-04-17",
    ),
    (
        "follow-ai-010",
        "model-wire",
        "Training budget cuts create a cautious outlook for frontier experiments",
        "训练预算削减让前沿模型实验前景转为谨慎",
        "Research managers said budget cuts and slower hiring are creating pressure on several frontier model experiments.",
        "研究负责人表示，预算削减和招聘放缓正在给多项前沿模型实验带来压力。",
        "2026-04-18",
    ),
    (
        "follow-ai-011",
        "infra-radar",
        "Inference chips win robotics contracts as edge AI demand grows",
        "推理芯片拿下机器人合同并受益于边缘AI需求增长",
        "Chip vendors said the contract win and healthy robotics demand are supporting a strong second-quarter outlook.",
        "芯片厂商表示，新合同的拿下和机器人需求的稳健增长，正在支撑更强的二季度展望。",
        "2026-04-18",
    ),
    (
        "follow-finance-006",
        "market-expectations",
        "Software stocks jump after investors celebrate an earnings beat",
        "投资者庆祝业绩超预期推动软件股走强",
        "Traders said the earnings beat and stronger guidance could boost software shares for another week.",
        "交易员表示，业绩超预期和更强的业绩指引，可能继续提振软件股表现。",
        "2026-04-14",
    ),
    (
        "follow-finance-007",
        "forex-flash",
        "Euro rebound improves margins and reduces pressure on importers",
        "欧元反弹改善利润率并缓解进口商压力",
        "Currency desks said the euro rebound is lowering near-term hedge losses and improving confidence among importers.",
        "外汇交易台表示，欧元反弹正在降低近期套保损失，并改善进口商信心。",
        "2026-04-15",
    ),
    (
        "follow-finance-008",
        "equity-sentiment",
        "Chipmakers tumble after a cautious capital-spending forecast",
        "芯片制造商因谨慎资本开支展望而下挫",
        "Funds said a cautious spending forecast and weaker order visibility triggered another tumble in chip shares.",
        "基金经理表示，谨慎的资本开支展望和偏弱的订单能见度引发了芯片股再度下挫。",
        "2026-04-16",
    ),
    (
        "follow-finance-009",
        "market-expectations",
        "Dividend banks keep support despite rate uncertainty",
        "高股息银行股在利率不确定下仍获支撑",
        "Strategists said healthy dividends and resilient balance sheets continue to support the sector despite rate uncertainty.",
        "策略师表示，尽管利率前景仍不确定，但稳健分红和有韧性的资产负债表仍在支撑该板块。",
        "2026-04-17",
    ),
    (
        "follow-finance-010",
        "forex-flash",
        "Yuan recovery helps airlines lock lower fuel-payment costs",
        "人民币回稳帮助航空公司锁定更低燃油支付成本",
        "Dealers said the yuan recovery and lower payment costs are improving cash-flow expectations for airlines.",
        "交易员表示，人民币回稳和更低的支付成本正在改善航空公司的现金流预期。",
        "2026-04-18",
    ),
    (
        "follow-finance-011",
        "equity-sentiment",
        "Small-cap shares remain under pressure after a weak financing update",
        "小盘股因融资更新偏弱而持续承压",
        "Investors said the weak financing update and another cautious outlook keep small-cap sentiment under pressure.",
        "投资者表示，偏弱的融资更新和再次转谨慎的展望让小盘股情绪持续承压。",
        "2026-04-18",
    ),
]

RSS_FEEDS = {
    "technology": "https://feeds.bbci.co.uk/news/technology/rss.xml",
    "business": "https://feeds.bbci.co.uk/news/business/rss.xml",
    "science": "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    "sport": "https://feeds.bbci.co.uk/sport/rss.xml",
    "health": "https://feeds.bbci.co.uk/news/health/rss.xml",
    "world": "https://feeds.bbci.co.uk/news/world/rss.xml",
    "culture": "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    "uk": "https://feeds.bbci.co.uk/news/uk/rss.xml",
    "europe": "https://feeds.bbci.co.uk/news/world/europe/rss.xml",
    "us-canada": "https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml",
    "asia": "https://feeds.bbci.co.uk/news/world/asia/rss.xml",
}

RSS_SOURCE_LABELS = {
    "technology": "BBC 科技",
    "business": "BBC 商业",
    "science": "BBC 科学环境",
    "sport": "BBC 体育",
    "health": "BBC 健康",
    "world": "BBC 国际",
    "culture": "BBC 文艺",
    "uk": "BBC 英国",
    "europe": "BBC 欧洲",
    "us-canada": "BBC 北美",
    "asia": "BBC 亚洲",
}


def get_seed_articles() -> list[dict]:
    return deepcopy(SEED_ARTICLES)


def get_followup_articles() -> list[dict]:
    return deepcopy(FOLLOWUP_ARTICLES)
